name: Build and deploy container to Azure Container App - email_service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/projbezpieczenstwo/email_service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: Projekt_Bezpieczeństwo
          containerAppName: email-service-app
          imageToDeploy: ghcr.io/projbezpieczenstwo/email_service:latest
